### ISSUE TITLE
Urdu Stop Words File

### ISSUE THREAD

**Issue by farooqzafarawan** [urduhack/urdu-stopwords#13]
I believe Urdu Stop words should be in a simple text file with just one word on one line. This way it would be lot easier to embed stop words for different applications and adding any stop word would be easier as well.
I have prepared a stop word list for wordcloud app and want to merge it with your list and make it as a standard stop words list.

**Comment by akkefa** [comment]
@farooqzafarawan Its a good idea. create a pull request.

**Comment by naeem9** [comment]
Both LISTS should be unified so that a comprehensive list can be made.

**Comment by naeem9** [comment]
There are 495 stopwords obtained after merging and removing duplicated in both lists which are listed below.
اب
ابھی
ابے
اپ
اپنا
اپنوں
اپنے
اپنے
اپنی
اتوار
اٹھا
ارب
اربویں
ارے
اس
اسکا
اسکے
اسکی
اسے
اسی
اف
افوہ
اکثر
اگر
اگرچہ
اگست
البتہ
الثانی
الحرام
السلام
الف
المکرم
ان
اندر
انکا
انکے
انکی
انہوں
انہی
انہیں
انھیں
اہاہا
او
اوپر
اور
اوہو
اوئے
اے
ایسا
ایسے
ایسی
ایک
آ
آپ
آتا
آتے
آتی
آگے
آمدید
آنا
آنسہ
آنے
آنی
آہ
آہا
آیا
آئے
آئی
آئیں
با
بار
بارے
بالکل
باہر
باوجود
بائیں
بج
بجے
بخیر
برسات
بڑا
بڑے
بڑی
بشرطیکہ
بعد
بعض
بغیر
بلکہ
بن
بنا
بناؤ
بند
بہار
بہت
بہتر
بھر
بھریں
بھی
بے
بیگم
پاس
پایا
پر
پس
پلیز
پہ
پہر
پہلا
پہلے
پہلی
پھاگن
پھر
پون
پونا
پونے
پونی
پیچھے
پیر
تا
تاکہ
تاہم
تب
تجھ
تجھے
تجھی
ترا
تری
تک
تلک
تم
تمام
تمہارا
تمہاروں
تمہارے
تمہاری
تمہیں
تمھارے
تمھیں
تہائی
تھا
تھے
تھی
تھیں
تو
تیرا
تیرے
تیری
تین
جا
جاتا
جاتے
جاتی
جانے
جانی
جاؤ
جائے
جائیں
جب
جبکہ
جدھر
جس
جسے
جن
جناب
جنہوں
جنہیں
جہاں
جو
جی
جیٹھ
جیسا
جیسوں
جیسے
جیسی
چاہتے
چاہے
چاہیئے
چاہئے
چکے
چکی
چکیں
چلا
چلو
چلے
چلیں
چناچہ
چند
چہارشنبہ
چوگنی
چونکہ
چیت
حالاں
حالانکہ
حصہ
حضرت
خاطر
خالی
خدا
خزاں
خواہ
خوب
خود
دائیں
درمیان
دریں
دکھائیں
دگنا
دو
دوران
دوسرا
دوسروں
دوسری
دوشنبہ
دوں
دونوں
دے
دی
دیا
دیتا
دیتے
دیتی
دیر
دیکھو
دیں
دینا
دینے
دینی
دیے
دیئے
ڈالا
ڈالنا
ڈالنے
ڈالنی
ڈالے
ڈالی
ذرا
ذریعے
رکھا
رکھتا
رکھتے
رکھتی
رکھنا
رکھنے
رکھنی
رکھو
رکھے
رکھی
رہ
رہا
رہتا
رہتے
رہتی
رہنا
رہنے
رہنی
رہو
رہے
رہی
رہیں
زیادہ
سا
ساتھ
ساڑھے
سامنے
سب
سبھی
سراسر
سکا
سکتا
سکتے
سلام
سمیت
سہ
سہی
سو
سوا
سوائے
سے
سی
شام
شاید
شکریہ
صاحب
صاحبہ
صرف
ضرور
طرح
طرف
طور
علاوہ
عین
فروری
فقط
فلاں
فی
قبل
قطا
کا
کاتک
کاش
کب
کبھی
کچھ
کدھر
کر
کرتا
کرتے
کرتی
کرم
کرنا
کرنے
کرو
کروں
کرے
کریں
کس
کسے
کسی
کل
کم
کن
کنہیں
کہ
کہا
کہاں
کہہ
کہے
کہی
کہیں
کو
کون
کونسا
کونسے
کوئی
کے
کی
کیا
کیسا
کیسے
کیوں
کیونکر
کیونکہ
کیے
کئے
گا
گرما
گرمی
گنا
گھنٹا
گھنٹوں
گھنٹے
گو
گویا
گے
گی
گیا
گئے
گئی
لا
لاتا
لاتے
لاتی
لانا
لانے
لانی
لایا
لائے
لائی
لگ
لگا
لگتا
لگتی
لگے
لگی
لگیں
لہذا
لو
لوجی
لوگوں
لے
لی
لیا
لیتا
لیتے
لیتی
لیکن
لیں
لیے
لئے
ماسوا
مت
مجھ
مجھے
مجھی
محترم
محترمہ
محترمی
محض
مرا
مرحبا
مرے
مری
مزید
مس
مسٹر
مسز
مطابق
مطلق
مکرمی
مگر
مگھر
مل
منٹ
منٹوں
مہربانی
میرا
میروں
میرے
میری
میں
نا
نزدیک
نما
نہ
نہایت
نہیں
نو
نومبر
نے
نیچے
نیز
ہاڑ
ہاں
ہائے
ہائیں
ہر
ہرچند
ہرگز
ہزار
ہفتہ
ہم
ہمارا
ہمارے
ہماری
ہمی
ہمیں
ہو
ہوا
ہوبہو
ہوتا
ہوتے
ہوتی
ہوتیں
ہوں
ہونا
ہونگے
ہونے
ہونی
ہوئے
ہوئی
ہوئیں
ہے
ہی
ہیلو
ہیں
و
وار
واسطے
واقعی
والا
والوں
والے
والی
واہ
وجہ
ورنہ
وعلیکم
وغیرہ
وگرنہ
ولے
وہ
وہاں
وہی
وہیں
ویسا
ویسے
ویں
یا
یات
یعنی
یک
یہ
یہاں
یہی
یہیں

**Comment by akkefa** [comment]
@muhammadfahid51 Improvement task for you.

- [ ] Merge this list with the old one and Normalize the characters first.
- [ ] Create a txt file of stop words. Each word by new line character.

**Comment by farooqzafarawan** [comment]
Ikram,

I forked stopwords repo from Delta-sigma and now Naeem has added extra words in the list and it is available as follows:

https://github.com/Mohibtech/urdu-stopwords

This is forked from Danyal Mirza repo who had a stopword list when I required and I extended it instead of creating a standalone list.

https://github.com/Delta-Sigma/urdu-stopwords

I would suggest extending the existing lists so that it stays synced across GitHub and credit is given where it is due.

Regards,

Farooq

________________________________
