### ISSUE TITLE
Need to verify Urdu stop words list

### ISSUE THREAD

**Issue by akkefa** [urduhack/urdu-stopwords#7]
### Add and Remove words 
We have 340+ Urdu stopwords. Do we need to remove some words from our list or not?

**Comment by rayyan17** [comment]
In my opinion following words should not be considered as stopwords:
{'تمام', 'گزشتہ', 'مکمل', 'شان', 'اگلے', 'پہلے', 'بننا', 'زیادہ', 'پاس', 'حاصل', 'ہمیشہ', 'ڈالا', 'اندر', 'نیچے', 'پوری', 'صورت', 'دوبارہ', 'ڈالی', 'غیر', 'ڈالیں', 'بظاہر', 'آخری', 'دسترس', 'قریب', 'مقابلے', 'استعمال', 'اوپر', 'دونوں', 'ڈالنا', 'ضرورت', 'جگہ', 'دو', 'پہلا', 'کافی', 'ضروری', 'بعد', 'یقینا', 'ختم'}

Based on these reasons:
1. We should not consider words which represent any kind of property or sentiment:  'مکمل', 'شان', 'کافی', 'ضروری'
2. Any word that can create a distinction between the two sentences:  'غیر', ..
3. The words that represent some kind of action: 'ڈالا', ..
4. Words that represents quantity:  'پوری', ..
5. Words that represent distance:  'قریب',

**Comment by farrukhbashir** [comment]
'دو' can be considered as a stop word in my opinion. It's individually useless no importance in a sentence

**Comment by farrukhbashir** [comment]
'ضروری' is also a stopword. 

There are need to add more stopwords. The list of words are given below

 لوجی
لوگ
لوگوں
لگتی
هلا
هیری
هیرے
وار
چکے
چکیں
چلے
چلیں
چلو
چلا
کہی
ہوچکی

In most of the cases, we have not removed all stop words but it varies situation to situation like when we find sentiment and use neural network then we mostly not remove all list of stopwords. So some words are part of stop words but not every time we used.

**Comment by akkefa** [comment]
@farrukhbashir Is  **ہوچکی**  is a single word or combination of two words?

**Comment by farrukhbashir** [comment]
combination of two words

M.Farrukh Bashir | Student(MSCS)
National University of Computer and Emerging Sciences
Farrukh.Bashirbw@gmail.com
03143636019

**Comment by akkefa** [comment]
@farrukhbashir then it should be two separate words ہو | چکی . What do you say?

**Comment by akkefa** [comment]
@rayyan17 @farrukhbashir I pushed the changes you mentioned in the comment.

**Comment by farrukhbashir** [comment]
Yes, it should be two separate words. Ok good.

M.Farrukh Bashir | Student(MSCS)
National University of Computer and Emerging Sciences
Farrukh.Bashirbw@gmail.com
03143636019

**Comment by akkefa** [comment]
@mirfan899 
Need to verify Urdu stop words list.

**Comment by mirfan899** [comment]
There is no clear definition of stop words. Mostly those words that are redundant, categorized into stop words.

**Comment by akkefa** [comment]
> There is no clear definition of stop words. Mostly those words that are redundant, categorized into stop words.

Just make sure this list does not contain any import word.

**Comment by mirfan899** [comment]
Stop words are good to go.

**Comment by urdutext** [comment]
Stopwords are those that are not considered as  keywords
Related:
consider removing words in written red color at this link
https://www.urduweb.org/mehfil/threads/110397/

**Comment by akkefa** [comment]
@urdutext can you come to chat https://gitter.im/urduhack/urduhack? Need to discuss a few things.

**Comment by akkefa** [comment]
@urdutext We removed those words which are not stopwords.

**Comment by urdutext** [comment]
> 
> 
> @urdutext can you come to chat https://gitter.im/urduhack/urduhack? Need to discuss a few things.

sure.
